### PR TITLE
Feature/bound 13 display board general

### PR DESCRIPTION
**Pull request by SCustodero**
add in display board function and add face down card to playing cards text

### CODE REVIEW

**Review by EthanThomas0523 — APPROVED** [review]
Great job, Sean! I like how you took that extra step to implement the back of the cards!

**Comment by SCustodero** [comment]
> Great job, Sean! I like how you took that extra step to implement the back of the cards!

Thanks Ethan!

**Review by georgiok741 — APPROVED** [review]
Great Work brother! Nice touch to add the "back of cards" in the new_playing_cards.txt file

**Comment by SCustodero** [comment]
> Great Work brother! Nice touch to add the "back of cards" in the new_playing_cards.txt file

Thank you sir

**Pull request merged**
