### PR TITLE
Feature/skare 35 flask

### PR DESCRIPTION
**Pull request by mccueki**
This is the first test run of flask implementation to the game. This will allow our python code to be used in html for a web interf. The game loop should be within the flask file. This test run reveals how to store players locally and return variables through html etc. File changes include a new python file flask_file.py and three html files index.html, game.html, and result.html. In the future, game.html will replace result.html

### CODE REVIEW

**Review by robcas12 — APPROVED** [review]
Requirement Satisfaction: Satisfies the requirements in the trello board. The Flask integration is great and will significantly increase the user experience. Great job!

Logic Errors: No major logic errors. Ensuring synchronization between the server-side game state and the client-side display without causing delays or inconsistencies will be important for a future sprint.

Test Coverage: No major test coverage issues. Testing for the effectiveness of the logic relying how player actions (raise, call, fold) are captured and updated in real time will be a good test for the next sprint as well.

Style Guides:  No major style guide issues.

**Comment by mccueki** [comment]
Thanks Robert!

**Review by Agwebberley — APPROVED** [review]
This looks great!  Maybe add a list of changes for a PR this big

**Review by sophianicolas — APPROVED** [review]
Thank you for your efforts! This looks great. There doesn’t seem to be any logic errors, and the flask_file.py file and modifications to CardGames are clear to follow.  This looks exciting to work with and see how to implement all current and future functionalities into the flask application.

**Comment by mccueki** [comment]
@Agwebberley lol got it

**Comment by mccueki** [comment]
@sophianicolas thank you!

**Pull request merged**
