### PR TITLE
feature/SKARE-46-Html-Raise

### PR DESCRIPTION
**Pull request by erinyooey**
Implemented raise logic in flask_file and created htmlraise_test file.

### CODE REVIEW

**Review by mccueki — APPROVED** [review]
Great work! Good error handling. This will be very useful.

**Review by robcas12 — COMMENTED** [review]
Requirement Satisfaction: Required all of the satisfactions of the task on the troll board
Logic Errors: No major Logic errors
Test Coverage: Covered edge cases for error handling 
Style Guides: No major style guide issues

Good job Erin !

**Review by robcas12 — APPROVED** [review]

**Comment by erinyooey** [comment]
Thank you!

**Comment by erinyooey** [comment]
Thanks!

**Pull request merged**
