### PR TITLE
Feature/bound 22 deck functionality

### PR DESCRIPTION
**Pull request by georgiok741**

### CODE REVIEW

**Review by EthanThomas0523 — COMMENTED** [review]
Great job, Georgio! I would suggest changing the deck names so it is clear which deck has which range of cards. So, for example, changing deck3 to HighRange, deck2 to MidRange, and deck 1 to LowRange.

**Comment by EthanThomas0523** [comment]
Great job, Georgio! I would suggest changing the deck names so it is clear which deck has which range of cards. So, for example, changing deck3 to HighRange, deck2 to MidRange, and deck 1 to LowRange.

**Review by EthanThomas0523 — CHANGES_REQUESTED** [review]
Great job, Georgio! I would suggest changing the deck names so it is clear which deck has which range of cards. So, for example, changing deck3 to HighRange, deck2 to MidRange, and deck 1 to LowRange.

**Comment by georgiok741** [comment]
> Great job, Georgio! I would suggest changing the deck names so it is clear which deck has which range of cards. So, for example, changing deck3 to HighRange, deck2 to MidRange, and deck 1 to LowRange.

Thanks Ethan, I went ahead and made the changes and added comments as well.

**Review by EthanThomas0523 — APPROVED** [review]

**Pull request merged**
